learning_rate:
  type: linspace
  setup:
    lower: 0.1
    upper: 0.3
    num: 3

use_test_dataset:
  type: switch

epochs:
  type: range
  setup:
    start: 10
    stop: 30
    step: 10

myvar:
  type: list
  setup:
    values: [1.0, 12.0, 8.0]
